apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: hello-spark
  namespace: default
spec:
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
  image: hello-spark:0.9.0
  mainApplicationFile: local:///opt/spark/work-dir/hello.py
  sparkVersion: "4.0.0"
  type: Python
  deps:
    pyFiles:
       - local:///opt/spark/work-dir/deps/cowsay-6.1-py3-none-any.whl
