apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: fare-prediction
  namespace: default
spec:
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: 512m
  image: fare-prediction:0.1.0
  mainApplicationFile: local:///opt/spark/work-dir/fare-prediction.py
  sparkVersion: 4.0.0
  type: Python
  